export const APP_PATHS = {
  root: '',
  auth: {
    base: 'auth',
    login: 'login',
    signup: 'signup',
    forgotPassword: 'forgot-password',
    verifyEmail: 'verify-email',
  },
  platform: {
    base: 'platform',
    overviewPlaceholder: 'overview-placeholder',
    tenants: 'tenants',
    newTenant: 'new',
    auditLogs: 'audit',
  },
  tenant: {
    base: 'tenant',
    select: 'select',
    overview: 'overview',
    conversations: 'conversations',
    conversationDetail: (id: string) => `conversations/${id}`,
    customers: 'customers',
    customerDetail: (id: string) => `customers/${id}`,
    aiAgent: 'ai-agent',
    aiAgentPrompt: 'ai-agent/prompt',
    knowledgeBase: 'knowledge-base',
    knowledgeBaseNew: 'knowledge-base/new',
    knowledgeBaseDetail: (id: string) => `knowledge-base/${id}`,
    knowledgeBaseEdit: (id: string) => `knowledge-base/${id}/edit`,
    integrations: 'integrations',
    integrationDetail: 'integrations/:slug',
    analytics: 'analytics',
    auditLogs: 'audit-logs',
    settings: 'settings',
    settingsTools: 'settings/tools',
    team: 'team',
    escalations: 'escalations',
    widgets: 'widgets',
    notifications: 'notifications',
  },
  invite: 'invite',
  notFound: '**',
} as const;
