export const APP_PATHS = {
  root: '',
  auth: {
    base: 'auth',
    login: 'login',
    signup: 'signup',
    forgotPassword: 'forgot-password',
    verifyEmail: 'verify-email',
  },
  platform: {
    base: 'platform',
    overviewPlaceholder: 'overview-placeholder',
    tenants: 'tenants',
    newTenant: 'new',
  },
  tenant: {
    base: 'tenant',
    select: 'select',
    overview: 'overview',
    conversations: 'conversations',
    conversationDetail: (id: string) => `conversations/${id}`,
    customers: 'customers',
    customerDetail: (id: string) => `customers/${id}`,
    aiAgent: 'ai-agent',
    knowledgeBase: 'knowledge-base',
    integrations: 'integrations',
    analytics: 'analytics',
    settings: 'settings',
    team: 'team',
    escalations: 'escalations',
  },
  invite: 'invite',
  notFound: '**',
} as const;
